# Generated by Django 4.1.2 on 2022-10-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(max_length=225)),
                ('whats', models.CharField(max_length=13)),
            ],
        ),
        migrations.DeleteModel(
            name='home',
        ),
    ]
